image: markhobson/maven-chrome:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build_and_test:
  tags: [testing]
  # before_script:
  # - export WEBDRIVER="/usr/bin/geckodriver"
  script:
    - echo "Building UI Automation project with maven"
    #- apt install firefox -y
    #- firefox --version
    #- which firefox
    #- which geckodriver
    #- cat /etc/os-release
    - mvn clean test
  timeout: 4h 30m
  artifacts:
      when: always
      paths:
        - target
        - ExtentReport
      expire_in: 1 week

# image: markhobson/maven-chrome:jdk-16

# build_and_test:
#   tags: [ui-test]
#   script:
#     - echo "Building UI Automation project with maven"
#     - mvn clean test
#   timeout: 2h 30m
#   artifacts:
#       when: always
#       paths:
#         - target
#         - ExtentReport
#       expire_in: 1 week
